config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  mount Lookbook::Engine, at: "/rails/lookbook" if Rails.env.development?

  constraints(IpConstraint) do
    # Weddings
    # --------
    root "weddings#index"

    resources :weddings, only: %i[index new create show] do
      resources :events, only: %i[new create edit update destroy]
      resources :guests, only: %i[index new edit create update destroy] do
        # Invitation
        # ----------
        get "invitation", to: "invitation/invitation#show"
      end
      resources :invitations, only: %i[index new create edit update destroy]
      resources :places, only: %i[index new create edit update destroy]
      resource :schedule, only: %i[show]
    end
  end

  # Invitations
  # -----------
  get "invitation/:id",
      to: "invitation/invitation#show",
      as: "invitation"
  post "invitation_state_transition",
       to: "invitation/invitation_state_transitions#create",
       as: "invitation_state_transition"
end

app/models/invitation.rb
# frozen_string_literal: true

class Invitation < ApplicationRecord
  include Decoratable
  include AASM

  # TODO: if used more often, move it to a concern
  def self.state_machine_events = aasm.events.map(&:name)

  def compatible_events = aasm.events(permitted: true).map(&:name)

  enum language: { en: "en", es: "es" }

  # Associations
  belongs_to :wedding, optional: false
  has_many :guests, dependent: :nullify

  # Validations
  validates :language, presence: true
  validates :guests, length: { minimum: 1 }
  validates :needs_travel_guide, inclusion: { in: [true, false] }
  validate :guests_in_wedding_guests_list, if: -> { wedding.present? }

  # State Machine
  aasm column: :state, timestamps: false, whiny_persistence: false do
    state :pending, initial: true
    state :delivered, :opened, :accepted, :declined, :cancelled

    event :deliver do
      transitions from: :pending, to: :delivered
    end

    event :open do
      transitions from: :pending, to: :opened
      transitions from: :delivered, to: :opened
    end

    event :accept do
      transitions from: :opened, to: :accepted
    end

    event :decline do
      transitions from: :opened, to: :declined
    end

    event :cancel do
      transitions from: :accepted, to: :cancelled
    end
  end

  private

  def guests_in_wedding_guests_list
    uninvited_guests = guests.reject { wedding.in_guests_list?(_1) }

    return if uninvited_guests.empty?

    errors.add(:guests, :guest_not_invited_to_wedding)
    uninvited_guests.each { _1.errors.add(:guests, :guest_not_invited_to_wedding) }
  end
end

app/controllers/invitation/application_controller.rb
# frozen_string_literal: true

class Invitation::ApplicationController < ApplicationController
  # Use special layout for invitation routes
  layout "invitation/layouts/application"
end

app/controllers/invitation/invitation_controller.rb
# frozen_string_literal: true

# Renders the client-side application representing the Wedding
# invitation for a specific +Guest+ of a specific +Wedding+
class Invitation::InvitationController < Invitation::ApplicationController
  # GET /invitation/<invitation-id>
  def show
    @invitation = Invitation.find(params[:id])
    @preview_mode = params.fetch(:preview_mode, false) == "true"

    I18n.locale = @invitation.language
    open_invitation if !@preview_mode && (@invitation.pending? || @invitation.delivered?)
  end

  private

  def open_invitation
    InvitationStateTransition.new(invitation: @invitation, event: :open).save
  end
end

app/controllers/invitation/invitation_state_transitions_controller.rb
# frozen_string_literal: true

class Invitation::InvitationStateTransitionsController < Invitation::ApplicationController
  # POST /invitation_state_transition
  def create
    @invitation_state_transition = InvitationStateTransition.new(
      event: invitation_state_transition_params[:event],
      invitation: Invitation.find(invitation_state_transition_params[:invitation_id])
    )

    if @invitation_state_transition.invitation.accepted? || @invitation_state_transition.save
      head :ok, content_type: "text/html"
    else
      head :unprocessable_entity, content_type: "text/html"
    end
  end

  private

  def invitation_state_transition_params = InvitationStateTransitionParameters.new(params[:invitation_state_transition])
end

app/controllers/invitations_controller.rb
# frozen_string_literal: true

class InvitationsController < ApplicationController
  # GET /weddings/<wedding-id>/invitations
  def index
    set_wedding
    @invitations = @wedding.invitations
  end

  # GET /weddings/<wedding-id>/invitations/new
  def new
    set_wedding
    @invitation = @wedding.invitations.new
  end

  # GET /weddings/<wedding-id>/invitations/<id>/edit
  def edit
    set_invitation
  end

  # POST /weddings/<wedding-id>/invitations
  def create
    set_wedding
    @invitation = @wedding.invitations.new(**invitation_parameters)

    if @invitation.save
      flash.now[:notice] = t("controllers.invitations_controller.create.notice")
      render status: :created
    else
      flash.now[:alert] = t("controllers.invitations_controller.create.alert")
      render status: :unprocessable_entity
    end
  end

  # PATCH /weddings/<wedding-id>/invitations/<id>
  def update
    set_invitation

    @invitation.assign_attributes(invitation_parameters) if can_update?

    if can_update? && @invitation.save
      flash.now[:notice] = t("controllers.invitations_controller.update.notice")
      render status: :ok
    else
      flash.now[:alert] = t("controllers.invitations_controller.update.alert")
      render status: :unprocessable_entity
    end
  end

  # DELETE /weddings/<wedding-id>/invitations/<id>
  def destroy
    set_invitation

    if @invitation.destroy
      flash.now[:notice] = t("controllers.invitations_controller.destroy.notice")
      render status: :ok
    else
      flash.now[:alert] = t("controllers.invitations_controller.destroy.alert")
      render status: :unprocessable_entity
    end
  end

  private

  def invitation_parameters
    @invitation_parameters ||= InvitationParameters.new(params[:invitation])
  end

  def set_wedding
    @wedding = Wedding.find(params[:wedding_id])
  end

  def set_invitation
    @invitation = Invitation.includes(:wedding).find_by!(wedding_id: params[:wedding_id], id: params[:id])
  end

  def can_update?
    if invitation_parameters.key?(:guest_ids)
      invitation_parameters[:guest_ids].present? && invitation_parameters[:guest_ids].any?
    else
      true
    end
  end
end

app/helpers/invitation/component_helper.rb
# frozen_string_literal: true

# Set of helpers for +Invitation::Common+ +ViewComponent+. These components
# are designed to be used as the regular +Common+ components, but in the scope
# of the +Invitation+ +Pages+
module Invitation::ComponentHelper
  def invitation_button_component(label:, size: :medium, scheme: :primary, **system_arguments, &)
    render(Invitation::Common::ButtonComponent.new(label:, size:, scheme:, **system_arguments), &)
  end

  def invitation_icon_button_component(icon:, size: :medium, scheme: :primary, **system_arguments)
    render(Invitation::Common::IconButtonComponent.new(icon:, size:, scheme:, **system_arguments))
  end
end

app/views/invitations/create.turbo_stream.haml
- if response.created?
  -# Hide Modal Component
  = turbo_stream.append(Invitations::EditComponent::Form::ID) do
    %div{ "data-common--modal-component-target": "autoClose" }

  -# Reload guests list via lazy-load turbo frame replacing current tab navigator
  = turbo_stream.replace(Common::TabNavigationComponent::TURBO_FRAME) do
    = turbo_frame_tag(Common::TabNavigationComponent::TURBO_FRAME, src: wedding_invitations_path(@wedding), loading: "lazy")
- else
  -# Reload form component with errors
  = turbo_stream.replace(Invitations::EditComponent::Form::ID) do
    = render Invitations::EditComponent::Form.new(wedding: @wedding, invitation: @invitation)

app/views/invitations/destroy.turbo_stream.haml
- if response.ok?
  -# Hide Modal Component
  = turbo_stream.append(Common::ModalComponent.stimulus_identifier) do
    %div{ "data-common--modal-component-target": "autoClose" }

  -# If wedding had one invitation before deletion
  - if @invitation.wedding.invitations.empty?
    = turbo_stream.replace(Common::TabNavigationComponent::TURBO_FRAME) do
      = turbo_frame_tag(Common::TabNavigationComponent::TURBO_FRAME, src: wedding_invitations_path(@invitation.wedding), loading: "lazy")
  - else
    = turbo_stream.remove(dom_id(@invitation))

app/views/invitations/edit.html.haml
= render Invitations::EditComponent.new(wedding: @invitation.wedding, invitation: @invitation)

app/views/invitations/index.html.haml
= render Invitations::IndexComponent.new(wedding: @wedding, invitations: @invitations)

app/views/invitations/new.html.haml
= render Invitations::EditComponent.new(wedding: @wedding, invitation: @invitation)

app/views/invitations/update.turbo_stream.haml
- if response.ok?
  -# Hide Modal Component
  = turbo_stream.append(Common::ModalComponent.stimulus_identifier) do
    %div{ "data-common--modal-component-target": "autoClose" }

  -# Reload invitations list via lazy-load turbo frame replacing current tab navigator
  = turbo_stream.replace(Common::TabNavigationComponent::TURBO_FRAME) do
    = turbo_frame_tag(Common::TabNavigationComponent::TURBO_FRAME, src: wedding_invitations_path(@invitation.wedding), loading: "lazy")
- else
  -# Reload form component with errors
  = turbo_stream.replace(Invitations::EditComponent::Form::ID) do
    = render Invitations::EditComponent::Form.new(wedding: @invitation.wedding, invitation: @invitation)