config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  mount Lookbook::Engine, at: "/rails/lookbook" if Rails.env.development?

  constraints(IpConstraint) do
    # Weddings
    # --------
    root "weddings#index"

    resources :weddings, only: %i[index new create show] do
      resources :events, only: %i[new create edit update destroy]
      resources :guests, only: %i[index new edit create update destroy] do
        # Invitation
        # ----------
        get "invitation", to: "invitation/invitation#show"
      end
      resources :invitations, only: %i[index new create edit update destroy]
      resources :places, only: %i[index new create edit update destroy]
      resource :schedule, only: %i[show]
    end
  end

  # Invitations
  # -----------
  get "invitation/:id",
      to: "invitation/invitation#show",
      as: "invitation"
  post "invitation_state_transition",
       to: "invitation/invitation_state_transitions#create",
       as: "invitation_state_transition"
end

app/models/place.rb
# frozen_string_literal: true

class Place < ApplicationRecord
  include Decoratable

  # Associations
  has_one :event, dependent: :nullify

  belongs_to :address, dependent: :destroy
  belongs_to :wedding, optional: true

  accepts_nested_attributes_for :address, allow_destroy: true

  # Validations
  validates :name, presence: true
  validates_associated :address
end

app/controllers/places_controller.rb
# frozen_string_literal: true

class PlacesController < ApplicationController
  # GET /weddings/<wedding-id>/places
  def index
    set_wedding
    @places = @wedding.places
  end

  # GET /weddings/<wedding-id>/new
  def new
    set_wedding
    @place = @wedding.places.new
  end

  # GET /weddings/<wedding-id>/places/<id>/edit
  def edit
    set_place
  end

  def create
    set_wedding
    @place = @wedding.places.new(**place_parameters)

    if @place.save
      flash.now[:notice] = t("controllers.places_controller.create.notice")
      render status: :created
    else
      flash.now[:alert] = t("controllers.places_controller.create.alert")
      render status: :unprocessable_entity
    end
  end

  # PATCH /weddings/<wedding-id>/places/<id>
  def update
    set_place
    @place.assign_attributes(place_parameters)

    if @place.save
      flash.now[:notice] = t("controllers.places_controller.update.notice")
      render status: :ok
    else
      flash.now[:alert] = t("controllers.places_controller.update.alert")
      render status: :unprocessable_entity
    end
  end

  # DELETE /weddings/<wedding-id>/places/<id>
  def destroy
    set_place

    if @place.destroy
      flash.now[:notice] = t("controllers.places_controller.destroy.notice")
      render status: :ok
    else
      flash.now[:alert] = t("controllers.places_controller.destroy.alert")
      render status: :unprocessable_entity
    end
  end

  private

  def set_wedding
    @wedding = Wedding.find(params[:wedding_id])
  end

  def set_place
    @place = Place.includes(:wedding).find_by!(wedding_id: params[:wedding_id], id: params[:id])
  end

  def place_parameters
    PlaceParameters.new(params[:place])
  end
end

app/views/places/create.turbo_stream.haml
- if response.created?
  -# Hide Modal Component
  = turbo_stream.append(Places::EditComponent::Form::ID) do
    %div{ "data-common--modal-component-target": "autoClose" }

  -# Reload guests list via lazy-load turbo frame replacing current tab navigator
  = turbo_stream.replace(Common::TabNavigationComponent::TURBO_FRAME) do
    = turbo_frame_tag(Common::TabNavigationComponent::TURBO_FRAME, src: wedding_places_path(@wedding), loading: "lazy")
- else
  -# Reload form component with errors
  = turbo_stream.replace(Places::EditComponent::Form::ID) do
    = render Places::EditComponent::Form.new(wedding: @wedding, place: @place)

app/views/places/destroy.turbo_stream.haml
- if response.ok?
  -# Hide Modal Component
  = turbo_stream.append(Places::EditComponent::Form::ID) do
    %div{ "data-common--modal-component-target": "autoClose" }

  -# If wedding had one guest before deletion
  - if @place.wedding.events.empty?
    = turbo_stream.replace(Common::TabNavigationComponent::TURBO_FRAME) do
      = turbo_frame_tag(Common::TabNavigationComponent::TURBO_FRAME, src: wedding_schedule_path(@place.wedding), loading: "lazy")
  - else
    = turbo_stream.remove(dom_id(@place))

app/views/places/edit.html.haml
= render Places::EditComponent.new(wedding: @place.wedding, place: @place)

app/views/places/index.html.haml
= render Places::IndexComponent.new(wedding: @wedding, places: @places)

app/views/places/new.html.haml
= render Places::EditComponent.new(wedding: @wedding, place: @place)

app/views/places/update.turbo_stream.haml
- if response.ok?
  -# Hide Modal Component
  = turbo_stream.append(Places::EditComponent::Form::ID) do
    %div{ "data-common--modal-component-target": "autoClose" }

  -# Reload guests list via lazy-load turbo frame replacing current tab navigator
  = turbo_stream.replace(Common::TabNavigationComponent::TURBO_FRAME) do
    = turbo_frame_tag(Common::TabNavigationComponent::TURBO_FRAME, src: wedding_places_path(@place.wedding), loading: "lazy")
- else
  -# Reload form component with errors
  = turbo_stream.replace(Places::EditComponent::Form::ID) do
    = render Places::EditComponent::Form.new(wedding: @place.wedding, place: @place)